### ISSUE TITLE
Code duplication 

### ISSUE THREAD

**Issue by anumpatel** [shreyamdg/LeetCodeEasy#1]
Duplicate code occurs at all insert* methods when head is null.
Better if a new separate method is created.

https://github.com/shreyamdg/LeetCodeEasy/blob/ea13391c4413d91b78698ee88fee96c05a97722d/src/linkedLists/LinkedList.java#L105

**Comment by shreyamdg** [comment]
Removed duplicate code. Commit hash: e3f6ae15e69c7d0198eccd1a8a6c170db8b9ce3e
